### ISSUE TITLE
Version on Hackage still requires base 4.7

### ISSUE THREAD

**Issue by seschwar** [erebe/systemd#1]
`systemd-1.0.0` on Hackage has `base == 4.7.*` as a dependency. This effectively prevents the package from easily being used with anything but GHC 7.8, even though it works perfectly fine with newer GHC versions.

It would be nice if you relaxed or updated the version bounds, so that the package can be installed without `cabal`'s or `stack`'s `allow-newer`.

**Comment by erebe** [comment]
Thanks for the reminder.
It should be good now, you can find the new version there 
https://hackage.haskell.org/package/systemd-1.0.2/

Let me know if you need something else
