### ISSUE TITLE
allow network-3.2

### ISSUE THREAD

**Issue by ysangkok** [erebe/systemd#12]
See

* https://github.com/commercialhaskell/stackage/issues/7381

This is one of the last remaining Stackage packages that doesn't accept network-3.2.

**Comment by erebe** [comment]
It should be good with latest version https://hackage.haskell.org/package/systemd-2.4.0

**Comment by ysangkok** [comment]
Perfect, thank you. Verified with GHC-9.10.1 and `cabal repl -b systemd -c 'network>=3.2'` and it works
