### ISSUE TITLE
Add shorthands notifyReloading and notifyStopping

### ISSUE THREAD

**Issue by basvandijk** [erebe/systemd#2]
Hi Erèbe, cool library! I'm using it in production.

It would be nice if you could add the shorthands: 

```haskell
notifyReloading :: IO (Maybe())
notifyReloading = notify False "RELOADING=1"

notifyStopping :: IO (Maybe())
notifyStopping = notify False "STOPPING=1"
```

Having support for `FDSTORE=1` and `FDNAME` would be nice as well but I haven't thought about a good API for that yet.

https://www.freedesktop.org/software/systemd/man/sd_notify.html#

**Comment by erebe** [comment]
I added those shortcuts and bumped the version to hackage (1.0.6 now)

I took a look at the implementation for FDSTORE and FDNAME in libsystemd, and sadly they use [ancillary data](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.hale001/ipv6d0151021873.htm) to pass file descriptors with the message and as far as I know there is no equivalent in Haskell for that.

I can add it but I have to add more c code (should I depend on libsystemd directly ?) and I have to find time to test it properly.

I am letting the issue open to see if I have time to tackle this

**Comment by erebe** [comment]
Hello, I have added the support for FDSTORE and FDNAME, you can have a look at it 
https://hackage.haskell.org/package/systemd . The new version is the 1.1.1

I tested the code on my machine with success, but tell me if it is working on your side too.

**Comment by basvandijk** [comment]
Nice work!

I'm using 1.0.6 at the moment. I will try out the FDSTORE functionality later.

Thanks a lot.
