### ISSUE TITLE
Tests fail on hardcoded directory

### ISSUE THREAD

**Issue by jkachmar** [erebe/systemd#3]
Currently this package's tests fail with the following error:
```
daemon-test: /home/erebe/log: openFile: does not exist (No such file or directory)
```

Likely caused by:
https://github.com/erebe/systemd/blob/master/test/Main.hs#L12-L13

**Comment by erebe** [comment]
Hello,
Sorry for the delay, I haven't seen the notification for this issue.
I will look into it in a few days.

**Comment by erebe** [comment]
Should be OK with the last version 1.2.0 on hackage
https://hackage.haskell.org/package/systemd
